/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fabriciosuarte.planets.api;


import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import io.javalin.Javalin;
import io.javalin.json.JavalinJson;
import static io.javalin.apibuilder.ApiBuilder.*;

import com.fabriciosuarte.planets.api.common.PropertyBag;
import com.fabriciosuarte.planets.api.controller.PlanetsController;
import com.fabriciosuarte.planets.api.application.Services;
import com.fabriciosuarte.planets.api.application.ApplicationServiceLocator;
import com.fabriciosuarte.planets.api.dataMapper.DataMapperLocator;
import com.fabriciosuarte.planets.api.dataMapper.DataMappers;

public class App {

    private static final int LISTENING_PORT = 7000;

    public static void main(String[] args) {

        //Starting and setting the server
        Javalin app = Javalin.create().start(LISTENING_PORT);

        //Setting Gson as the Json parser
        Gson gson = new GsonBuilder().create();
        JavalinJson.setFromJsonMapper(gson::fromJson);
        JavalinJson.setToJsonMapper(gson::toJson);

        //Mapping endpoints
        app.routes( () -> {
                    path("planets", () -> {
                        post(PlanetsController::createPlanet);
                        get(PlanetsController::getAllPlanets);
                        path("query/:name", () -> get(PlanetsController::getPlanetByName));
                        path(":id", () -> {
                            get(PlanetsController::getPlanet);
                            delete(PlanetsController::deletePlanet);
                        });
                    });
                });

        //Setting service locators
        Services.setLocator(new ApplicationServiceLocator());
        DataMappers.setLocator(new DataMapperLocator());

        //Setting application properties
        PropertyBag.getInstance().setString("dbConnectionString", "mongodb://localhost:27017");
        PropertyBag.getInstance().setString("databaseName", "planets-api");
    }
}
